# Day 9

## Problem 1

In the hightmap, there are points which is lower than any adjacent location (up, down, left and right).
Risk level of a low point is 1 plus its height.
Find all the low points and get the sum of the risk levels of all low points on the heightmap. 

In [1]:
import numpy as np

According to Marijn's code, it is possible to use "converters" to make a text into a list of characters!

In [34]:
heightmap = np.loadtxt('example.txt', converters={0:list}, encoding='utf-8', dtype='int')
"""
heightmap_in_num = np.loadtxt('example.txt', delimiter='/n', dtype='str')
test = np.empty([len(heightmap_in_num),len(heightmap_in_num[0])])
for line in range(0, len(heightmap_in_num)):
    for char in range(0, len(heightmap_in_num[line])):
        test[line][char] = heightmap_in_num[line][char]
test = np.array(test, dtype='int')
"""
print(heightmap)

[[2 1 9 9 9 4 3 2 1 0]
 [3 9 8 7 8 9 4 9 2 1]
 [9 8 5 6 7 8 9 8 9 2]
 [8 7 6 7 8 9 6 7 8 9]
 [9 8 9 9 9 6 5 6 7 8]]


In [140]:
# how to map (BTW)
def text_list2(text1, text2):
	city = []
	for i in range(len(text1)):
		city.append(text1[i])
		city.append(text2[i])
	return(city)

z = map(text_list2, ('oslo', 'los','newyork'), ('yokohama', 'kawasaki','takasaki'))
print(list(z))

[['o', 'y', 's', 'o', 'l', 'k', 'o', 'o'], ['l', 'k', 'o', 'a', 's', 'w'], ['n', 't', 'e', 'a', 'w', 'k', 'y', 'a', 'o', 's', 'r', 'a', 'k', 'k']]


Let's learn from Marijn's code (again, but it is super good resource to learn!!)

In [54]:
print(heightmap[1:]) # from the 2nd (index = 1) row to the end

[[3 9 8 7 8 9 4 9 2 1]
 [9 8 5 6 7 8 9 8 9 2]
 [8 7 6 7 8 9 6 7 8 9]
 [9 8 9 9 9 6 5 6 7 8]]


In [56]:
print(heightmap[:,1:]) # all the rows but from the 2nd colomn (index = 1) to the end

[[1 9 9 9 4 3 2 1 0]
 [9 8 7 8 9 4 9 2 1]
 [8 5 6 7 8 9 8 9 2]
 [7 6 7 8 9 6 7 8 9]
 [8 9 9 9 6 5 6 7 8]]


`&=` -> store the result of AND logic.

In [61]:
logic_result = [1,2,3]
logic_input = [1,1,3]
for i in range(0,3):
    logic_result[i] &= logic_input[i]
print(logic_result)

[1, 0, 3]


In [62]:
logic_input_1 = [1,2,3]
logic_input_2 = [1,1,3]
logic_result = [1,1,1]
for i in range(0,3):
    logic_result[i] &= logic_input_1[i] == logic_input_2[i]
print(logic_result)

[1, 0, 1]


In [67]:
low_position = np.ones_like(heightmap, dtype='bool')
print(low_position)

low_position[1:] &= (heightmap[1:]-heightmap[:-1]) < 0
low_position[:-1] &= (heightmap[:-1]-heightmap[1:]) < 0
low_position[:,1:] &= (heightmap[:,1:]-heightmap[:,:-1]) < 0
low_position[:,:-1] &= (heightmap[:,:-1]-heightmap[:,1:]) < 0

print(low_position)

[[ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]
 [ True  True  True  True  True  True  True  True  True  True]]
[[False  True False False False False False False False  True]
 [False False False False False False False False False False]
 [False False  True False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False  True False False False]]


In [72]:
# filtering by a boolean array (https://numpy.org/doc/stable/reference/arrays.indexing.html?highlight=filter#boolean-array-indexing)
print(heightmap[low_position.nonzero()]+1)

[2 1 6 6]


In [75]:
def low_pos_score(input):
    heightmap = np.loadtxt(input, converters={0:list}, encoding='utf-8', dtype='int')
    low_position = np.ones_like(heightmap, dtype='bool')

    low_position[1:] &= (heightmap[1:]-heightmap[:-1]) < 0
    low_position[:-1] &= (heightmap[:-1]-heightmap[1:]) < 0
    low_position[:,1:] &= (heightmap[:,1:]-heightmap[:,:-1]) < 0
    low_position[:,:-1] &= (heightmap[:,:-1]-heightmap[:,1:]) < 0

    score_array = (heightmap[low_position.nonzero()]+1)
    return(sum(score_array))
 

In [76]:
low_pos_score('input.txt')

514

## Problem 2

Find the 3 largest bensins and multiply sizes.


Again, let's learn from Marijn's code (https://gist.github.com/wmvanvliet/129b8246b7e9236926862c1d6603b5b6)

In [85]:
map_height, map_width = heightmap.shape # return the number or rows and columns
print("heightmap: \n", heightmap)
print("map_height: ", map_height)
print("map_width: ", map_width)

heightmap: 
 [[2 1 9 9 9 4 3 2 1 0]
 [3 9 8 7 8 9 4 9 2 1]
 [9 8 5 6 7 8 9 8 9 2]
 [8 7 6 7 8 9 6 7 8 9]
 [9 8 9 9 9 6 5 6 7 8]]
map_height:  5
map_width:  10


In [86]:
print(low_position)

[[False  True False False False False False False False  True]
 [False False False False False False False False False False]
 [False False  True False False False False False False False]
 [False False False False False False False False False False]
 [False False False False False False  True False False False]]


In [100]:
seeds = np.where(low_position,2,0)
print("seeds with output specified: \n", seeds)

seeds = np.where(low_position)
# When only condition is provided, this function is a shorthand for np.asarray(condition).nonzero(). 
# zip() in conjunction with the * operator can be used to unzip a list:
print("seeds output NOT specified, resulting in arrays:", seeds)
seeds = zip(np.where(low_position))
print("zip seeds: ", seeds)
seeds = list(zip(np.where(low_position))) # 
print("list zip seeds: ", seeds)
seeds = list(zip(*np.where(low_position)))
print("list unzip seeds: ", seeds)
print(list(zip(*citylist)))



seeds with output specified: 
 [[0 2 0 0 0 0 0 0 0 2]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 2 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 2 0 0 0]]
seeds output NOT specified, resulting in arrays: (array([0, 0, 2, 4]), array([1, 9, 2, 6]))
zip seeds:  <zip object at 0x1100a0b80>
list zip seeds:  [(array([0, 0, 2, 4]),), (array([1, 9, 2, 6]),)]
list unzip seeds:  [(0, 1), (0, 9), (2, 2), (4, 6)]
[('t', 'o'), ('o', 's'), ('k', 'a'), ('y', 'k'), ('o', 'a')]


In [147]:
basins = list() # prepare an empty list to store basins
basin = set()  # A set object is an unordered collection of distinct hashable objects. 

from collections import deque, Counter, defaultdict # deque: Returns a new deque object initialized left-to-right (using append()) with data from iterable. 

for seed in seeds:
    print("element in seeds is in the form of tuple",[seed])
    to_check = deque([seed])
    print(to_check.popleft())

print(heightmap[(0,1)]) # it is possible to surround index by ()


element in seeds is in the form of tuple [(0, 1)]
(0, 1)
element in seeds is in the form of tuple [(0, 9)]
(0, 9)
element in seeds is in the form of tuple [(2, 2)]
(2, 2)
element in seeds is in the form of tuple [(4, 6)]
(4, 6)
1


Deque:

https://qiita.com/ryosuke0825/items/bbc5c0673e6c6c958d66

it seems that it is much faster to compute using deque. 

In [127]:
# understand how "continue" works in "while"-loop
while_i_list = deque([1,2,3,4,5])
while_j = 0
while_basin = set()

while len(while_i_list)>0 and while_j < 3:
    point = while_i_list.popleft() # the most left element of while_i_list is assigned as "point", and "while_i_list" is now the rest (after removing the most left element).
    print("point is ", point, "while_i_list is now ", while_i_list)
    if point == 2:
        print("point is 2 and thus continue to the next round")
        continue # means that the process below this is not done, but goes to the next round.
    while_basin.add(point)
    print("while_basin is ",while_basin)
    while_j += 1
    print("while_j is ", while_j) # when while_j is 3, no more round is to run.


point is  1 while_i_list is now  deque([2, 3, 4, 5])
while_basin is  {1}
while_j is  1
point is  2 while_i_list is now  deque([3, 4, 5])
point is 2 and thus continue to the next round
point is  3 while_i_list is now  deque([4, 5])
while_basin is  {1, 3}
while_j is  2
point is  4 while_i_list is now  deque([5])
while_basin is  {1, 3, 4}
while_j is  3


In [150]:
for seed in seeds:
    basin = set()
    to_check = deque([seed]) # set does not have order of the elements, so here it uses "deque"
    i = 0
    # print("--- now seed is", seed)
    while len(to_check) > 0 and i < 100000:
        point = to_check.popleft()
        # print("point now is ", point)
        if heightmap[point] == 9:
            # print("the point height is 9")
            continue

        basin.add(point)
        # print("basin now is ", basin)
        row, col = point
        neighbours = set()
        if row > 0:
            neighbours.add((row - 1, col))
        if row < map_height - 1:
            neighbours.add((row + 1, col))
        if col > 0:
            neighbours.add((row, col - 1))
        if col < map_width - 1:
            neighbours.add((row, col + 1))
        # print("neighbours now is ", neighbours)
        to_check.extend(neighbours - basin)
        # print("to_check now is ", to_check)
        i += 1
    basins.append(basin)
    # print("---------- basins now is ", basins)

# basins = list() # to reset it
print("basins:", basins)
print('Day 9, part2:', np.product(sorted([len(b) for b in basins])[-3:]))

basins: [{(0, 1), (1, 0), (0, 0)}, {(0, 7), (1, 8), (0, 9), (0, 6), (2, 9), (0, 5), (1, 6), (0, 8), (1, 9)}, {(2, 4), (1, 2), (2, 1), (3, 4), (4, 1), (3, 1), (1, 4), (3, 0), (2, 3), (3, 3), (2, 2), (3, 2), (2, 5), (1, 3)}, {(3, 8), (2, 7), (4, 9), (3, 7), (4, 6), (4, 5), (4, 8), (3, 6), (4, 7)}]
Day 9, part2: 1134


This problem is a really difficult one.
I did not notice (or just did not read the instruction carefully), but it seems all the basins are surrounded by "9".

Still, it seems that the code above checks again and again the same point that is found to be 9 whenever it is considered as a neighbor. 
isn't it possible to avoid checking everytime a point is 9 or not? Isn't it possible to check (i, j) according to its "previous" neighbors, such as (i-1, j) and (i, j-1)?





In [144]:
# learning about how "defaultdict" works
from collections import defaultdict
import random
import string
n = 10
val_str = ''.join([random.choice(string.ascii_lowercase) for i in range(n)])
print(val_str)

d = defaultdict(lambda:9)
for key in val_str:
    d[key] += 1

print(d)


fyevhrujyv
defaultdict(<function <lambda> at 0x1115361f0>, {'f': 10, 'y': 11, 'e': 10, 'v': 11, 'h': 10, 'r': 10, 'u': 10, 'j': 10})


In [151]:
basin_id_array = np.zeros_like(heightmap)
print(basin_id_array)

[[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [225]:
list_test = [0,1,2,3,4,5]
list_test.append(0)
# list_test[1]=2
# list_test.pop(-1)
print(list_test)

[0, 1, 2, 3, 4, 5, 0]


In [250]:
heightmap_example = np.loadtxt("example.txt", converters={0:list}, encoding='utf-8', dtype='int')
print(heightmap_example)
heightmap_example[heightmap_example==heightmap_example[0,2]] = 11
print(heightmap_example)
unique_values, occurrence_count = np.unique(heightmap_example, return_counts=True) 
print(unique_values)
print(occurrence_count)   

[[2 1 9 9 9 4 3 2 1 0]
 [3 9 8 7 8 9 4 9 2 1]
 [9 8 5 6 7 8 9 8 9 2]
 [8 7 6 7 8 9 6 7 8 9]
 [9 8 9 9 9 6 5 6 7 8]]
[[ 2  1 11 11 11  4  3  2  1  0]
 [ 3 11  8  7  8 11  4 11  2  1]
 [11  8  5  6  7  8 11  8 11  2]
 [ 8  7  6  7  8 11  6  7  8 11]
 [11  8 11 11 11  6  5  6  7  8]]
[ 0  1  2  3  4  5  6  7  8 11]
[ 1  3  4  2  2  2  5  6 10 15]


In [231]:
heightmap = np.loadtxt("example.txt", converters={0:list}, encoding='utf-8', dtype='int')
basin_id_array = np.zeros_like(heightmap)
basin_id = 0
# the first row, first column
i = 0
j = 0
basin_id_total = [0]

if heightmap[i,j] != 9:
    basin_id += 1
    basin_id_array[i,j] = basin_id
    basin_id_total.append(1)

# the first row, second to last column
for j in range(1,len(heightmap[0])):
    if heightmap[0,j] != 9:
        if heightmap[0,j-1] == 9:
            basin_id += 1
            basin_id_total.append(0)
        basin_id_array[0,j] = basin_id
        basin_id_total[basin_id] += 1

# the rest
for i in range(1,len(heightmap)):
    # first column
    j = 0
    if heightmap[i,j] != 9:
        if heightmap[i-1,j] != 9:
            basin_id_array[i,j] = basin_id_array[i-1,j]
            basin_id_total[basin_id_array[i,j]] += 1
        else:
            basin_id += 1
            basin_id_array[i,j] = basin_id
            basin_id_total.append(1)
    # second to the last column
    for j in range(1,len(heightmap[0])):
        if heightmap[i,j] != 9: 
            if heightmap[i-1,j] !=9 and heightmap[i,j-1]!=9:
                basin_id_array[i,j] = basin_id_array[i-1,j]
                if basin_id_array[i,j-1] > basin_id_array[i,j]:
                    basin_id_array[i,j-1] = basin_id_array[i-1,j]
                    basin_id -= 1
                    basin_id_total.pop(-1)
                    basin_id_total[basin_id_array[i,j-1]] +=1
            elif heightmap[i-1,j] !=9 and heightmap[i,j-1]==9:
                basin_id_array[i,j] = basin_id_array[i-1,j]
            elif heightmap[i-1,j] ==9 and heightmap[i,j-1]!=9:
                basin_id_array[i,j] = basin_id_array[i,j-1]
            elif heightmap[i-1,j] ==9 and heightmap[i,j-1]==9:
                basin_id += 1
                basin_id_array[i,j] = basin_id
                basin_id_total.append(0)
            basin_id_total[basin_id_array[i,j]] += 1
        else:
            print("heightmap[i,j] is ",heightmap[i,j])
print("end of row ", i+1)
print(basin_id_array)
print("basin_id_total: ", basin_id_total)

basin_id_total.sort(reverse= True)
product = basin_id_total[0]*basin_id_total[1]*basin_id_total[2]
print("part 2:", product)
#*basin_id_total_sorted[1]*basin_id_total_sorted[2])


heightmap[i,j] is  9
heightmap[i,j] is  9
heightmap[i,j] is  9
heightmap[i,j] is  9
heightmap[i,j] is  9
heightmap[i,j] is  9
heightmap[i,j] is  9
heightmap[i,j] is  9
heightmap[i,j] is  9
heightmap[i,j] is  9
end of row  5
[[1 1 0 0 0 2 2 2 2 2]
 [1 0 3 3 3 0 2 0 2 2]
 [0 3 3 3 3 3 0 4 0 2]
 [3 3 3 3 3 0 4 4 4 0]
 [0 3 0 0 0 4 4 4 4 4]]
basin_id_total:  [0, 3, 9, 14, 9]
part 2: 1134


OK, it seems it is working. (well, afterward, I found that it actually did not work in the real input file and changed to make it work no matter what the above and left spots are)

In [221]:
heightmap = np.loadtxt("input.txt", converters={0:list}, encoding='utf-8', dtype='int')
basin_id_array = np.zeros_like(heightmap)
basin_id_array.shape


(100, 100)

In [331]:
def three_largest_basins(input):
    heightmap = np.loadtxt(input, converters={0:list}, encoding='utf-8', dtype='int')
    basin_id_array = np.zeros_like(heightmap)
    basin_id = 0

    if heightmap[0,0] != 9:
        basin_id += 1
        basin_id_array[0,0] = basin_id

    # the first row, second to last column
    for j in range(1,len(heightmap[0])):
        if heightmap[0,j] != 9:
            if heightmap[0,j-1] == 9:
                basin_id += 1
            basin_id_array[0,j] = basin_id

    # the rest
    for i in range(1,len(heightmap)):
        # first column
        j = 0
        if heightmap[i,j] != 9:
            if heightmap[i-1,j] != 9:
                basin_id_array[i,j] = basin_id_array[i-1,j]
            else:
                basin_id += 1
                basin_id_array[i,j] = basin_id
        # second to the last column
        for j in range(1,len(heightmap[0])):
            if heightmap[i,j] != 9: 
                if heightmap[i-1,j] !=9 and heightmap[i,j-1]!=9: # above point's basin id could be both lower or higher than the left point.
                    if basin_id_array[i,j-1] > basin_id_array[i,j]:
                        basin_id_array[i,j] = basin_id_array[i-1,j]
                        basin_id_array[basin_id_array==basin_id_array[i,j-1]] = basin_id_array[i,j]
                    elif basin_id_array[i,j-1] < basin_id_array[i,j]:
                        basin_id_array[i,j] = basin_id_array[i,j-1]
                        basin_id_array[basin_id_array==basin_id_array[i-1,j]] = basin_id_array[i-1,j]
                    else:
                        basin_id_array[i,j] = basin_id_array[i,j-1]
                elif heightmap[i-1,j] !=9 and heightmap[i,j-1]==9:
                    basin_id_array[i,j] = basin_id_array[i-1,j]
                elif heightmap[i-1,j] ==9 and heightmap[i,j-1]!=9:
                    basin_id_array[i,j] = basin_id_array[i,j-1]
                elif heightmap[i-1,j] ==9 and heightmap[i,j-1]==9:
                    basin_id += 1
                    basin_id_array[i,j] = basin_id
    unique_ids, id_count = np.unique(basin_id_array, return_counts=True)

    id_count_from_one = id_count[1:]
    sorted_id_count = np.sort(id_count_from_one)[-3:]
    product = np.prod(sorted_id_count)
    # print(product)

In [332]:
three_largest_basins("input.txt")

In [322]:
def marijn_day_nine(input):
    heightmap = np.loadtxt(input, encoding='utf8', converters={0: list}, dtype='int')
    is_lowpoint = np.ones_like(heightmap, dtype='bool')
    is_lowpoint[1:] &= (heightmap[:-1] - heightmap[1:]) > 0
    is_lowpoint[:-1] &= (heightmap[1:] - heightmap[:-1]) > 0
    is_lowpoint[:, 1:] &= (heightmap[:, :-1] - heightmap[:, 1:]) > 0
    is_lowpoint[:, :-1] &= (heightmap[:, 1:] - heightmap[:, :-1]) > 0
    # print('Day 9, part 1:', np.sum(1 + heightmap[is_lowpoint]))

    map_height, map_width = heightmap.shape
    seeds = list(zip(*np.where(is_lowpoint)))
    basins = list()

    for seed in seeds:
        basin = set()
        to_check = deque([seed])
        i = 0
        while len(to_check) > 0 and i < 100000:
            point = to_check.popleft()
            if heightmap[point] == 9:
                continue

            basin.add(point)
            row, col = point
            neighbours = set()
            if row > 0:
                neighbours.add((row - 1, col))
            if row < map_height - 1:
                neighbours.add((row + 1, col))
            if col > 0:
                neighbours.add((row, col - 1))
            if col < map_width - 1:
                neighbours.add((row, col + 1))
            to_check.extend(neighbours - basin)
            i += 1
        basins.append(basin)
    # print('Day 9, part2:', np.product(sorted([len(b) for b in basins])[-3:]))

In [323]:
%%timeit
marijn_day_nine("input.txt")

102 ms ± 190 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [326]:
# Radovan's solution
def radovan_day_nine(input):
    from collections import defaultdict


    def neighbors(position):
        i, j = position
        return [(i + 1, j), (i - 1, j), (i, j + 1), (i, j - 1)]


    def read_map(file_name):
        lines = open(file_name, "r").read().splitlines()

        # can be any number higher than 8
        heightmap = defaultdict(lambda: 9)

        for i, line in enumerate(lines):
            for j, c in enumerate(line):
                heightmap[(i, j)] = int(c)

        return heightmap


    def find_local_minima(heightmap):
        local_minima = []
        for (k, v) in list(heightmap.items()):
            if all([v < heightmap[n] for n in neighbors(k)]):
                local_minima.append(k)
        return local_minima


    def num_neighbors_below_9(position, heightmap):
        # we turn current position to 9 to make sure the recursion does not visit
        # this position again
        n = 1
        heightmap[position] = 9
        for neighbor in neighbors(position):
            if heightmap[neighbor] < 9:
                n += num_neighbors_below_9(neighbor, heightmap)
        return n


    # if __name__ == "__main__":
    # when uncomment above, tab the below
    heightmap = read_map("input.txt")

    local_minima = find_local_minima(heightmap)

    # print("part 1:", sum([heightmap[k] + 1 for k in local_minima]))

    basin_sizes = map(lambda p: num_neighbors_below_9(p, heightmap), local_minima)
    a, b, c, *_ = list(sorted(basin_sizes, reverse=True))

# print("part 2:", a * b * c)

In [333]:
%%timeit
three_largest_basins("input.txt")

37.5 ms ± 105 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [329]:
%%timeit
marijn_day_nine("input.txt")

103 ms ± 1.32 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [330]:
%%timeit
radovan_day_nine("input.txt")

13.9 ms ± 189 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)
