# Summary (Day 04)

## Problem 1

Get the score of the first winning board.

In [4]:
def first_winning_score(input_file):
    import numpy as np
    ### Step 1 and 2
    # get the "calls" list
    calls = np.loadtxt(input_file, dtype = 'int', delimiter = ',', max_rows = 1)
    print("calls are ", calls)
    type(calls[0])

    ### Step 3
    # how many boards are there?
    boards_pre = np.loadtxt(input_file, dtype = 'int', skiprows = 2)
    total_boards = int(len(boards_pre)/5) 
    print("we have ", total_boards, " boards")

    ### Step 4
    # prepare bords to store
    boards = np.zeros((total_boards,5,5), dtype="int")
    for i in range(0,total_boards):
        boards[i] = np.loadtxt(input_file, dtype = 'int', skiprows = 2+i*6, max_rows = 5)
    # print("boards are \n",boards)

    mark = np.zeros((total_boards,5,5),int)
    check_sum_row = np.zeros((total_boards,1,5),int)
    check_sum_column = np.zeros((total_boards,1,5),int)
    check_bingo = np.zeros((total_boards,2,5),int)
    check_bingo_sum = [0]*total_boards
    bingo = 0
    for i in range(0,len(calls)):
        print("round ", i+1)
        check_sum_row = np.zeros((total_boards,1,5),int)
        mark[boards == calls[i]] = 1
        # print(mark)
        for b in range(0,total_boards):
            check_sum_row[b][0]=[sum(mark[b][row]) for row in range(0,5)]
            # print("check_sum_row for", b, " is", check_sum_row[b][0])
            check_sum_column[b][0]=np.sum(mark[b],axis=0)
            # print("check_sum_column for", b, " is", check_sum_column[b][0])
            check_bingo[b][0]=np.where(check_sum_row[b][0] == 5, 1, 0)
            check_bingo[b][1]=np.where(check_sum_column[b][0] == 5, 1, 0)
            check_bingo_sum[b]=sum(check_bingo[b][0])+sum(check_bingo[b][1])
            # print("check_bingo_sum for", b, " is", check_bingo_sum[b])
            if check_bingo_sum[b] == 1:
                print(mark[b])
                print("bingo!! winning board is", b+1)
                bingo = 1
                break
        # print("check_sum_row are:\n", check_sum_row)
        # print("check_bingo are:\n", check_bingo)
        # print("check_bingo_sum are:\n", check_bingo_sum)
        if bingo == 1:
            break
    # it took long time..
    # calculate the sum of the remaining values of the winning board
    print(boards[b])
    print(boards[b][mark[b]==0])
    remaining = boards[b][mark[b] == 0].sum()
    print("remaining is ",remaining)
    score = remaining * calls[i]
    print("score is ", score)
    return score

In [5]:
first_winning_score("input.txt")

calls are  [91 17 64 45  8 13 47 19 52 68 63 76 82 44 28 56 37  2 78 48 32 58 72 53
  9 85 77 89 36 22 49 86 51 99  6 92 80 87  7 25 31 66 84  4 98 67 46 61
 59 79  0  3 38 27 23 95 20 35 14 30 26 33 42 93 12 57 11 54 50 75 90 41
 88 96 40 81 24 94 18 39 70 34 21 55  5 29 71 83  1 60 74 69 10 62 43 73
 97 65 15 16]
we have  100  boards
round  1
round  2
round  3
round  4
round  5
round  6
round  7
round  8
round  9
round  10
round  11
round  12
round  13
round  14
round  15
round  16
round  17
round  18
round  19
round  20
round  21
round  22
round  23
round  24
round  25
round  26
round  27
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [1 1 1 1 1]]
bingo!! winning board is 16
[[82  5 38 41 95]
 [70 52 11 21 51]
 [81 20  0 14 83]
 [57 36 60 59 42]
 [77 13 85 32 63]]
[ 5 38 41 95 70 11 21 51 81 20  0 14 83 57 36 60 59 42]
remaining is  784
score is  60368


60368

## Problem 2

Get the score of the last winning board

In [6]:
def last_winning_score(input_file):
    import numpy as np
    ### Step 1 and 2
    # get the "calls" list
    calls = np.loadtxt("input.txt", dtype = 'int', delimiter = ',', max_rows = 1)
    print("calls are ", calls)
    type(calls[0])

    ### Step 3
    # how many boards are there?
    boards_pre = np.loadtxt("input.txt", dtype = 'int', skiprows = 2)
    total_boards = int(len(boards_pre)/5) 
    print("we have ", total_boards, " boards")

    ### Step 4
    # prepare bords to store
    boards = np.zeros((total_boards,5,5), dtype="int")
    for i in range(0,total_boards):
        boards[i] = np.loadtxt("input.txt", dtype = 'int', skiprows = 2+i*6, max_rows = 5)
    # print("boards are \n",boards)

    mark = np.zeros((total_boards,5,5),int)
    check_sum_row = np.zeros((total_boards,1,5),int)
    check_sum_column = np.zeros((total_boards,1,5),int)
    check_bingo = np.zeros((total_boards,2,5),int)
    check_bingo_sum = [0]*total_boards
    bingo = 0
    remaining = np.zeros((len(calls),total_boards),bool)
    # we need the
    for i in range(0,len(calls)):
        print("round ", i+1)
        check_sum_row = np.zeros((total_boards,1,5),int)
        mark[boards == calls[i]] = 1
        # print(mark)
        for b in range(0,total_boards):
            check_sum_row[b][0]=[sum(mark[b][row]) for row in range(0,5)]
            # print("check_sum_row for", b, " is", check_sum_row[b][0])
            check_sum_column[b][0]=np.sum(mark[b],axis=0)
            # print("check_sum_column for", b, " is", check_sum_column[b][0])
            check_bingo[b][0]=np.where(check_sum_row[b][0] == 5, 1, 0)
            check_bingo[b][1]=np.where(check_sum_column[b][0] == 5, 1, 0)
            check_bingo_sum[b]=sum(check_bingo[b][0])+sum(check_bingo[b][1])
            # print("check_bingo_sum for", b, " is", check_bingo_sum[b])
            if check_bingo_sum[b] >= 1:
                # print(mark[b])
                remaining[i][b] = True
                # print("bingo!! winning board is", b+1)
                bingo = bingo + 1            
        # print("check_sum_row are:\n", check_sum_row)
        # print("check_bingo are:\n", check_bingo)
        # print("check_bingo_sum are:\n", check_bingo_sum)
        if bingo == total_boards:
            for b in range(0,total_boards):
                if remaining[i][b] != remaining[i-1][b]:
                    print("the last board that won is ", b+1)
                    break
            break
        else: 
            bingo = 0
    # it took long time..
    # calculate the sum of the remaining values of the winning board
    print(boards[b])
    print(boards[b][mark[b]==0])
    remaining_nr_sum = boards[b][mark[b] == 0].sum()
    print("the sum of the remaining nr is ",remaining_nr_sum)
    score = remaining_nr_sum * calls[i]
    print("score is ", score)
    return(score)

In [7]:
last_winning_score("input.txt")

calls are  [91 17 64 45  8 13 47 19 52 68 63 76 82 44 28 56 37  2 78 48 32 58 72 53
  9 85 77 89 36 22 49 86 51 99  6 92 80 87  7 25 31 66 84  4 98 67 46 61
 59 79  0  3 38 27 23 95 20 35 14 30 26 33 42 93 12 57 11 54 50 75 90 41
 88 96 40 81 24 94 18 39 70 34 21 55  5 29 71 83  1 60 74 69 10 62 43 73
 97 65 15 16]
we have  100  boards
round  1
round  2
round  3
round  4
round  5
round  6
round  7
round  8
round  9
round  10
round  11
round  12
round  13
round  14
round  15
round  16
round  17
round  18
round  19
round  20
round  21
round  22
round  23
round  24
round  25
round  26
round  27
round  28
round  29
round  30
round  31
round  32
round  33
round  34
round  35
round  36
round  37
round  38
round  39
round  40
round  41
round  42
round  43
round  44
round  45
round  46
round  47
round  48
round  49
round  50
round  51
round  52
round  53
round  54
round  55
round  56
round  57
round  58
round  59
round  60
round  61
round  62
round  63
round  64
round  65
round  66
round  67
r

17435