# Day 05

## Problem 1

Find the number of points where at least two lines overlap. Think only about vertical and horizontal lines.

### Steps to take
1. get the input lines and convert each line to a combination of [x1, y1] and [x2, y2].
2. get the min and max of x and y
3. make an array of x(max)-x(min)+1 * y(max)-y(min)+1 with 0
4. x-round: 1) filter combinations where x1 == x2, 2) for each x kept, add 1 to the y values from min to max in the array made in step 3
5. y-round
6. count up positions where >=2 in the array

In [14]:
import numpy as np

with open("example.txt", "r") as input_text:
    lines_text = input_text.read()

lines_text_list = lines_text.split("\n")
#lines_text_no_arrow = lines_text_list.split(" -> ").
    
# np.loadtxt((line_text.replace(), delimiter=" -> ")
print(lines_text_list)

['0,9 -> 5,9', '8,0 -> 0,8', '9,4 -> 3,4', '2,2 -> 2,1', '7,0 -> 7,4', '6,4 -> 2,0', '0,9 -> 2,9', '3,4 -> 1,4', '0,0 -> 8,8', '5,5 -> 8,2']


In [18]:
lines_value_str = [lines_text_list[i].replace(" -> ", ",") for i in range(0,len(lines_text_list))]
print(lines_value_str)

['0,9,5,9', '8,0,0,8', '9,4,3,4', '2,2,2,1', '7,0,7,4', '6,4,2,0', '0,9,2,9', '3,4,1,4', '0,0,8,8', '5,5,8,2']


## Let's learn from Marijn's solution!

Marijn's solution is at https://gist.github.com/wmvanvliet/129b8246b7e9236926862c1d6603b5b6

In [59]:
# x = lambda s : s.split(',')
lines_test = np.loadtxt('example.txt', delimiter=' -> ', converters={0: lambda s: s.split(','), 1: lambda s: s.split(',')}, encoding='utf8', dtype='int')
print(lines_test)
# print(np.sum(lines_test[0:2] >5))
# x1, x2 = 1, 2 # this is also a convenient way of writing! 2 variables can be defined in one line!
# xdir = 1 if x1 < x2 else 0 # it is convenient way of writing!!
# print(xdir)

field = np.zeros((10,10), dtype = 'int')
print(np.arange(0,9)[5:0:-2])
field[(np.arange(0, 4)[::1], np.arange(2, 6)[::-1])] += 1
print(field)

[[[0 9]
  [5 9]]

 [[8 0]
  [0 8]]

 [[9 4]
  [3 4]]

 [[2 2]
  [2 1]]

 [[7 0]
  [7 4]]

 [[6 4]
  [2 0]]

 [[0 9]
  [2 9]]

 [[3 4]
  [1 4]]

 [[0 0]
  [8 8]]

 [[5 5]
  [8 2]]]
[5 3 1]
[[0 0 0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 0 1 0 0]
 [0 0 0 0 0 0 1 0 0 0]
 [0 0 0 0 0 1 0 0 0 0]
 [0 0 0 0 1 0 0 0 0 0]
 [0 0 0 1 0 0 0 0 0 0]
 [0 0 1 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]


In [44]:
## Day 5
def split_on_comma(x):
    return x.split(',')

lines = np.loadtxt('input.txt', delimiter=' -> ', converters={0: split_on_comma, 1: split_on_comma}, encoding='utf8', dtype='int')
# numpy.loadtxt(converters=) --> converters: convert the value in the specified column by the specified function. it is defined in dictionary {(column): (function)}
# For example, in this case, after one line is divided by "->", then column 0 is '0,9' for the first line, colum 1 is '5,9'. 
# Marijn defined in the first 2 lines "split_on_comma" function, which is applied in the dictionary.
# lambda works also fine.
width, height = lines.max(axis=(0, 1)) + 1
# axis=0 --> row, axis=1 --> column
field_part1 = np.zeros((height, width), dtype='int')
field_part2 = np.zeros_like(field_part1)
# zeros_like(array) -> make an array of 0 in the same shape of the referred array.

for [x1, y1], [x2, y2] in lines:
    xmin, xmax = min(x1, x2), max(x1, x2) + 1 # +1 is necessary because when indexing, the last index should be +1 (e.g., until "before" the last index)
    ymin, ymax = min(y1, y2), max(y1, y2) + 1
    xdir = 1 if x1 < x2 else -1
    ydir = 1 if y1 < y2 else -1

    if x1 == x2 or y1 == y2:  # horizontal or vertical line
        field_part1[ymin:ymax, xmin:xmax] += 1 # using indexing for rows (y) and columns (x)
        field_part2[ymin:ymax, xmin:xmax] += 1
    else:  # Diagonal line 
        # NB!in this challenge, all the lines are either of horizontal, vertical or diagonal.
        field_part2[(np.arange(ymin, ymax)[::ydir], np.arange(xmin, xmax)[::xdir])] += 1

print('Day 5, part 1:', np.sum(field_part1 >= 2)) # it counts the number of elements in an array that satisfy the condition.
print('Day 5, part 2', np.sum(field_part2 >= 2))

Day 5, part 1: 6283
Day 5, part 2 18864
